variables:
  # pipeline variables
  service_connection: "assignment-prod"
  backend_service_connection: "assignment-prod"
  spn_app_id: "<<spn apllication ID >>"
  spn_obj_id: "<<spn object id>>"

  # servive connection for docker container registory
  service_connection_acr: resistory-prod
  container_registory_name: assignmentweprod
  container_image_name: react-and-spring-data-rest
  container_image_tag: latest
  container_registory_sku: Basic
  containerAppName: assignment-app-name-we-prod
  infra_rg_name: rg-infra-we-prod-01

  # Resource for backend
  backend_resource_group_name: rg-backend-infra-prod
  backend_storage_infra_name: stassignweprod

  # Log analytics
  log_analytics_name: log-analytics-prod
