variables:
  # pipeline variables
  service_connection: "assignment-test"
  backend_service_connection: "assignment-test"
  spn_app_id: "<<spn apllication ID >>"
  spn_obj_id: "<<spn object id>>"

  # servive connection for docker container registory
  service_connection_acr: resistory-test
  container_registory_name: assignmentwetest
  container_image_name: react-and-spring-data-rest
  container_image_tag: latest
  container_registory_sku: Basic
  containerAppName: assignment-app-name-we-test
  infra_rg_name: rg-infra-we-test-01

  # Resource for backend
  backend_resource_group_name: rg-backend-infra-test
  backend_storage_infra_name: stassignwetest

  # Log analytics
  log_analytics_name: log-analytics-test
